// Code generated by protoc-gen-go. DO NOT EDIT.
// source: chaincode.proto

package service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	peer "github.com/hyperledger/fabric/protos/peer"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WaitForTxCommit int32

const (
	WaitForTxCommit_DEFAULT WaitForTxCommit = 0
	// without waiting for transaction commit event
	WaitForTxCommit_NONE WaitForTxCommit = 1
	// wait for all msp id peers
	WaitForTxCommit_MSPID_ALL WaitForTxCommit = 2
	// wait for any msp id peer
	WaitForTxCommit_MSPID_ANY WaitForTxCommit = 3
	// wait for all endorsers
	WaitForTxCommit_ENDORSER_ALL WaitForTxCommit = 4
	// wait for any endorser
	WaitForTxCommit_ENDORSER_ANY WaitForTxCommit = 5
	// wait for all network peer
	WaitForTxCommit_NETWORK_ALL WaitForTxCommit = 6
	// wait for any network peer
	WaitForTxCommit_NETWORK_ANY WaitForTxCommit = 7
)

var WaitForTxCommit_name = map[int32]string{
	0: "DEFAULT",
	1: "NONE",
	2: "MSPID_ALL",
	3: "MSPID_ANY",
	4: "ENDORSER_ALL",
	5: "ENDORSER_ANY",
	6: "NETWORK_ALL",
	7: "NETWORK_ANY",
}

var WaitForTxCommit_value = map[string]int32{
	"DEFAULT":      0,
	"NONE":         1,
	"MSPID_ALL":    2,
	"MSPID_ANY":    3,
	"ENDORSER_ALL": 4,
	"ENDORSER_ANY": 5,
	"NETWORK_ALL":  6,
	"NETWORK_ANY":  7,
}

func (x WaitForTxCommit) String() string {
	return proto.EnumName(WaitForTxCommit_name, int32(x))
}

func (WaitForTxCommit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{0}
}

// Invocation type
type InvocationType int32

const (
	// Query / simulate only
	InvocationType_QUERY InvocationType = 0
	// Invoke  / simulate and broadcast to orderer
	InvocationType_INVOKE InvocationType = 1
)

var InvocationType_name = map[int32]string{
	0: "QUERY",
	1: "INVOKE",
}

var InvocationType_value = map[string]int32{
	"QUERY":  0,
	"INVOKE": 1,
}

func (x InvocationType) String() string {
	return proto.EnumName(InvocationType_name, int32(x))
}

func (InvocationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{1}
}

// Chaincode  invocation input
type ChaincodeInput struct {
	// Chaincode name
	Chaincode string `protobuf:"bytes,1,opt,name=chaincode,proto3" json:"chaincode,omitempty"`
	// Channel name
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Input contains the arguments for invocation.
	Args [][]byte `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	// TransientMap contains data (e.g. cryptographic material) that might be used
	// to implement some form of application-level confidentiality. The contents
	// of this field are supposed to always be omitted from the transaction and
	// excluded from the ledger.
	Transient map[string][]byte `protobuf:"bytes,4,rep,name=transient,proto3" json:"transient,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Hint for tx commit waiting policy
	WaitForTxCommit      WaitForTxCommit `protobuf:"varint,5,opt,name=wait_for_tx_commit,json=waitForTxCommit,proto3,enum=service.WaitForTxCommit" json:"wait_for_tx_commit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChaincodeInput) Reset()         { *m = ChaincodeInput{} }
func (m *ChaincodeInput) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInput) ProtoMessage()    {}
func (*ChaincodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{0}
}

func (m *ChaincodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeInput.Unmarshal(m, b)
}
func (m *ChaincodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeInput.Marshal(b, m, deterministic)
}
func (m *ChaincodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeInput.Merge(m, src)
}
func (m *ChaincodeInput) XXX_Size() int {
	return xxx_messageInfo_ChaincodeInput.Size(m)
}
func (m *ChaincodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeInput proto.InternalMessageInfo

func (m *ChaincodeInput) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *ChaincodeInput) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChaincodeInput) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ChaincodeInput) GetTransient() map[string][]byte {
	if m != nil {
		return m.Transient
	}
	return nil
}

func (m *ChaincodeInput) GetWaitForTxCommit() WaitForTxCommit {
	if m != nil {
		return m.WaitForTxCommit
	}
	return WaitForTxCommit_DEFAULT
}

// Chaincode event locator
type ChaincodeEventLocator struct {
	// Chaincode name
	Chaincode string `protobuf:"bytes,1,opt,name=chaincode,proto3" json:"chaincode,omitempty"`
	// Channel name
	Channel string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Block range
	Block                *BlockRange `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChaincodeEventLocator) Reset()         { *m = ChaincodeEventLocator{} }
func (m *ChaincodeEventLocator) String() string { return proto.CompactTextString(m) }
func (*ChaincodeEventLocator) ProtoMessage()    {}
func (*ChaincodeEventLocator) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{1}
}

func (m *ChaincodeEventLocator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeEventLocator.Unmarshal(m, b)
}
func (m *ChaincodeEventLocator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeEventLocator.Marshal(b, m, deterministic)
}
func (m *ChaincodeEventLocator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeEventLocator.Merge(m, src)
}
func (m *ChaincodeEventLocator) XXX_Size() int {
	return xxx_messageInfo_ChaincodeEventLocator.Size(m)
}
func (m *ChaincodeEventLocator) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeEventLocator.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeEventLocator proto.InternalMessageInfo

func (m *ChaincodeEventLocator) GetChaincode() string {
	if m != nil {
		return m.Chaincode
	}
	return ""
}

func (m *ChaincodeEventLocator) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

func (m *ChaincodeEventLocator) GetBlock() *BlockRange {
	if m != nil {
		return m.Block
	}
	return nil
}

type BlockRange struct {
	// from block
	From int64 `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	// to block
	To                   int64    `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRange) Reset()         { *m = BlockRange{} }
func (m *BlockRange) String() string { return proto.CompactTextString(m) }
func (*BlockRange) ProtoMessage()    {}
func (*BlockRange) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{2}
}

func (m *BlockRange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRange.Unmarshal(m, b)
}
func (m *BlockRange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRange.Marshal(b, m, deterministic)
}
func (m *BlockRange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRange.Merge(m, src)
}
func (m *BlockRange) XXX_Size() int {
	return xxx_messageInfo_BlockRange.Size(m)
}
func (m *BlockRange) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRange.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRange proto.InternalMessageInfo

func (m *BlockRange) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *BlockRange) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

type ChaincodeExec struct {
	Type                 InvocationType  `protobuf:"varint,1,opt,name=type,proto3,enum=service.InvocationType" json:"type,omitempty"`
	Input                *ChaincodeInput `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ChaincodeExec) Reset()         { *m = ChaincodeExec{} }
func (m *ChaincodeExec) String() string { return proto.CompactTextString(m) }
func (*ChaincodeExec) ProtoMessage()    {}
func (*ChaincodeExec) Descriptor() ([]byte, []int) {
	return fileDescriptor_97136ef4b384cc22, []int{3}
}

func (m *ChaincodeExec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeExec.Unmarshal(m, b)
}
func (m *ChaincodeExec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeExec.Marshal(b, m, deterministic)
}
func (m *ChaincodeExec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeExec.Merge(m, src)
}
func (m *ChaincodeExec) XXX_Size() int {
	return xxx_messageInfo_ChaincodeExec.Size(m)
}
func (m *ChaincodeExec) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeExec.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeExec proto.InternalMessageInfo

func (m *ChaincodeExec) GetType() InvocationType {
	if m != nil {
		return m.Type
	}
	return InvocationType_QUERY
}

func (m *ChaincodeExec) GetInput() *ChaincodeInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func init() {
	proto.RegisterEnum("service.WaitForTxCommit", WaitForTxCommit_name, WaitForTxCommit_value)
	proto.RegisterEnum("service.InvocationType", InvocationType_name, InvocationType_value)
	proto.RegisterType((*ChaincodeInput)(nil), "service.ChaincodeInput")
	proto.RegisterMapType((map[string][]byte)(nil), "service.ChaincodeInput.TransientEntry")
	proto.RegisterType((*ChaincodeEventLocator)(nil), "service.ChaincodeEventLocator")
	proto.RegisterType((*BlockRange)(nil), "service.BlockRange")
	proto.RegisterType((*ChaincodeExec)(nil), "service.ChaincodeExec")
}

func init() { proto.RegisterFile("chaincode.proto", fileDescriptor_97136ef4b384cc22) }

var fileDescriptor_97136ef4b384cc22 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0x8d, 0xff, 0xc1, 0x8f, 0x21, 0x01, 0x6b, 0x7e, 0x6d, 0x6a, 0xa1, 0xaa, 0x42, 0x1c, 0x5a,
	0x9a, 0xaa, 0x10, 0xd1, 0x4b, 0x94, 0x56, 0xaa, 0x92, 0xe0, 0x48, 0x28, 0xd4, 0x24, 0x1b, 0xd2,
	0x88, 0x13, 0x32, 0xce, 0x06, 0x2c, 0xc0, 0x6b, 0xad, 0x17, 0x12, 0x7a, 0xec, 0xb9, 0xdf, 0xa3,
	0x5f, 0xb3, 0xf2, 0x02, 0x26, 0xee, 0x3f, 0x55, 0xb9, 0xcd, 0xbe, 0x79, 0x33, 0xfb, 0xde, 0xec,
	0x0e, 0x14, 0xbd, 0x91, 0xeb, 0x07, 0x1e, 0xbb, 0xa1, 0xb5, 0x90, 0x33, 0xc1, 0x30, 0x1b, 0x51,
	0x3e, 0xf7, 0x3d, 0x5a, 0x3a, 0x1a, 0xfa, 0x62, 0x34, 0x1b, 0xd4, 0x3c, 0x36, 0xad, 0x8f, 0x16,
	0x21, 0xe5, 0x13, 0x7a, 0x33, 0xa4, 0xbc, 0x7e, 0xeb, 0x0e, 0xb8, 0xef, 0xd5, 0x25, 0x3b, 0xaa,
	0x87, 0x94, 0xf2, 0x38, 0x0e, 0x59, 0xe4, 0x4e, 0xfa, 0x9c, 0x46, 0x21, 0x0b, 0xa2, 0x55, 0xaf,
	0xd2, 0xc7, 0x7f, 0x6f, 0x91, 0xc8, 0xe8, 0xd3, 0x39, 0x0d, 0xc4, 0xb2, 0x41, 0xe5, 0xbb, 0x0a,
	0x85, 0x93, 0x75, 0xa6, 0x15, 0x84, 0x33, 0x81, 0xcf, 0x21, 0x97, 0x70, 0x2d, 0xa5, 0xac, 0x54,
	0x73, 0x64, 0x03, 0xa0, 0x05, 0x59, 0x6f, 0xe4, 0x06, 0x01, 0x9d, 0x58, 0xaa, 0xcc, 0xad, 0x8f,
	0x88, 0xa0, 0xbb, 0x7c, 0x18, 0x59, 0x5a, 0x59, 0xab, 0x6e, 0x13, 0x19, 0x63, 0x13, 0x72, 0x82,
	0xbb, 0x41, 0xe4, 0xd3, 0x40, 0x58, 0x7a, 0x59, 0xab, 0xe6, 0x1b, 0x2f, 0x6b, 0x2b, 0xff, 0xb5,
	0xf4, 0xbd, 0xb5, 0xee, 0x9a, 0x68, 0x07, 0x82, 0x2f, 0xc8, 0xa6, 0x10, 0x6d, 0xc0, 0x3b, 0xd7,
	0x17, 0xfd, 0x5b, 0xc6, 0xfb, 0xe2, 0xbe, 0xef, 0xb1, 0xe9, 0xd4, 0x17, 0x96, 0x51, 0x56, 0xaa,
	0x85, 0x86, 0x95, 0xb4, 0xbb, 0x76, 0x7d, 0x71, 0xca, 0x78, 0xf7, 0xfe, 0x44, 0xe6, 0x49, 0xf1,
	0x2e, 0x0d, 0x94, 0x3e, 0x40, 0x21, 0x7d, 0x07, 0x9a, 0xa0, 0x8d, 0xe9, 0x62, 0x65, 0x32, 0x0e,
	0xf1, 0x09, 0x18, 0x73, 0x77, 0x32, 0xa3, 0xd2, 0xdc, 0x36, 0x59, 0x1e, 0x0e, 0xd5, 0x03, 0xa5,
	0xf2, 0x05, 0x9e, 0x26, 0x82, 0xed, 0x78, 0x82, 0x6d, 0xe6, 0xb9, 0x82, 0xf1, 0x47, 0xcf, 0xeb,
	0x35, 0x18, 0x83, 0x09, 0xf3, 0xc6, 0x96, 0x56, 0x56, 0xaa, 0xf9, 0xc6, 0xff, 0x89, 0x91, 0xe3,
	0x18, 0x25, 0x6e, 0x30, 0xa4, 0x64, 0xc9, 0xa8, 0xec, 0x03, 0x6c, 0xc0, 0x78, 0xd0, 0xb7, 0x9c,
	0x4d, 0x65, 0x9d, 0x46, 0x64, 0x8c, 0x05, 0x50, 0x05, 0xb3, 0x74, 0x89, 0xa8, 0x82, 0x55, 0xc6,
	0xb0, 0xb3, 0x51, 0x7b, 0x4f, 0x3d, 0x7c, 0x03, 0xba, 0x58, 0x84, 0x4b, 0x81, 0x85, 0xc6, 0xb3,
	0xe4, 0xb2, 0x56, 0x30, 0x8f, 0x7d, 0xf8, 0x2c, 0xe8, 0x2e, 0x42, 0x4a, 0x24, 0x09, 0xdf, 0x82,
	0xe1, 0xc7, 0x6f, 0x22, 0x25, 0xe7, 0x1f, 0xb0, 0xd3, 0x4f, 0x46, 0x96, 0xac, 0xbd, 0x6f, 0x0a,
	0x14, 0x7f, 0x9a, 0x3e, 0xe6, 0x21, 0xdb, 0xb4, 0x4f, 0x8f, 0xae, 0xda, 0x5d, 0x73, 0x0b, 0xff,
	0x03, 0xdd, 0xe9, 0x38, 0xb6, 0xa9, 0xe0, 0x0e, 0xe4, 0x3e, 0x5d, 0x9e, 0xb7, 0x9a, 0xfd, 0xa3,
	0x76, 0xdb, 0x54, 0x1f, 0x1c, 0x9d, 0x9e, 0xa9, 0xa1, 0x09, 0xdb, 0xb6, 0xd3, 0xec, 0x90, 0x4b,
	0x9b, 0x48, 0x82, 0x9e, 0x46, 0x9c, 0x9e, 0x69, 0x60, 0x11, 0xf2, 0x8e, 0xdd, 0xbd, 0xee, 0x90,
	0x33, 0x49, 0xc9, 0xa4, 0x00, 0xa7, 0x67, 0x66, 0xf7, 0x5e, 0x41, 0x21, 0xed, 0x0a, 0x73, 0x60,
	0x5c, 0x5c, 0xd9, 0xa4, 0x67, 0x6e, 0x21, 0x40, 0xa6, 0xe5, 0x7c, 0xee, 0x9c, 0xd9, 0xa6, 0xd2,
	0xf8, 0xaa, 0x42, 0x2e, 0x71, 0x84, 0x07, 0xa0, 0xcb, 0x49, 0xed, 0xfe, 0xea, 0x36, 0xc6, 0x4b,
	0xd6, 0x72, 0x65, 0xa2, 0xda, 0xf9, 0x6a, 0x19, 0xc9, 0x6a, 0x17, 0xf1, 0x10, 0x8c, 0x8b, 0x19,
	0xe5, 0x0b, 0xfc, 0xd3, 0xa0, 0xfe, 0x52, 0xfb, 0x1e, 0x32, 0xb1, 0xd8, 0x31, 0x7d, 0x4c, 0xf1,
	0x31, 0x64, 0xe4, 0x57, 0x8c, 0xf0, 0xc5, 0x6f, 0x44, 0x3f, 0xf8, 0xa4, 0xa5, 0xdd, 0x75, 0x8f,
	0x74, 0x7a, 0x5f, 0x19, 0x64, 0x64, 0xe2, 0xdd, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x04,
	0x77, 0x5c, 0xa8, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChaincodeClient is the client API for Chaincode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChaincodeClient interface {
	// Exec: Query or Invoke
	Exec(ctx context.Context, in *ChaincodeExec, opts ...grpc.CallOption) (*peer.ProposalResponse, error)
	// Query chaincode on home peer. Do NOT send to orderer.
	Query(ctx context.Context, in *ChaincodeInput, opts ...grpc.CallOption) (*peer.ProposalResponse, error)
	// Invoke chaincode on peers, according to endorsement policy and the SEND to orderer
	Invoke(ctx context.Context, in *ChaincodeInput, opts ...grpc.CallOption) (*peer.ProposalResponse, error)
	// Chaincode events stream
	Events(ctx context.Context, in *ChaincodeEventLocator, opts ...grpc.CallOption) (Chaincode_EventsClient, error)
}

type chaincodeClient struct {
	cc *grpc.ClientConn
}

func NewChaincodeClient(cc *grpc.ClientConn) ChaincodeClient {
	return &chaincodeClient{cc}
}

func (c *chaincodeClient) Exec(ctx context.Context, in *ChaincodeExec, opts ...grpc.CallOption) (*peer.ProposalResponse, error) {
	out := new(peer.ProposalResponse)
	err := c.cc.Invoke(ctx, "/service.Chaincode/Exec", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaincodeClient) Query(ctx context.Context, in *ChaincodeInput, opts ...grpc.CallOption) (*peer.ProposalResponse, error) {
	out := new(peer.ProposalResponse)
	err := c.cc.Invoke(ctx, "/service.Chaincode/Query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaincodeClient) Invoke(ctx context.Context, in *ChaincodeInput, opts ...grpc.CallOption) (*peer.ProposalResponse, error) {
	out := new(peer.ProposalResponse)
	err := c.cc.Invoke(ctx, "/service.Chaincode/Invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chaincodeClient) Events(ctx context.Context, in *ChaincodeEventLocator, opts ...grpc.CallOption) (Chaincode_EventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Chaincode_serviceDesc.Streams[0], "/service.Chaincode/Events", opts...)
	if err != nil {
		return nil, err
	}
	x := &chaincodeEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Chaincode_EventsClient interface {
	Recv() (*peer.ChaincodeEvent, error)
	grpc.ClientStream
}

type chaincodeEventsClient struct {
	grpc.ClientStream
}

func (x *chaincodeEventsClient) Recv() (*peer.ChaincodeEvent, error) {
	m := new(peer.ChaincodeEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChaincodeServer is the server API for Chaincode service.
type ChaincodeServer interface {
	// Exec: Query or Invoke
	Exec(context.Context, *ChaincodeExec) (*peer.ProposalResponse, error)
	// Query chaincode on home peer. Do NOT send to orderer.
	Query(context.Context, *ChaincodeInput) (*peer.ProposalResponse, error)
	// Invoke chaincode on peers, according to endorsement policy and the SEND to orderer
	Invoke(context.Context, *ChaincodeInput) (*peer.ProposalResponse, error)
	// Chaincode events stream
	Events(*ChaincodeEventLocator, Chaincode_EventsServer) error
}

func RegisterChaincodeServer(s *grpc.Server, srv ChaincodeServer) {
	s.RegisterService(&_Chaincode_serviceDesc, srv)
}

func _Chaincode_Exec_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeExec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaincodeServer).Exec(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Chaincode/Exec",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaincodeServer).Exec(ctx, req.(*ChaincodeExec))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chaincode_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaincodeServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Chaincode/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaincodeServer).Query(ctx, req.(*ChaincodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chaincode_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChaincodeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChaincodeServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Chaincode/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChaincodeServer).Invoke(ctx, req.(*ChaincodeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Chaincode_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChaincodeEventLocator)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChaincodeServer).Events(m, &chaincodeEventsServer{stream})
}

type Chaincode_EventsServer interface {
	Send(*peer.ChaincodeEvent) error
	grpc.ServerStream
}

type chaincodeEventsServer struct {
	grpc.ServerStream
}

func (x *chaincodeEventsServer) Send(m *peer.ChaincodeEvent) error {
	return x.ServerStream.SendMsg(m)
}

var _Chaincode_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Chaincode",
	HandlerType: (*ChaincodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exec",
			Handler:    _Chaincode_Exec_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Chaincode_Query_Handler,
		},
		{
			MethodName: "Invoke",
			Handler:    _Chaincode_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _Chaincode_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "chaincode.proto",
}
